//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class UsuarioModel
{
    public int Id { get; set; }
    public string Correo { get; set; }
    public string NombreUsuario { get; set; }
    public string Password { get; set; }
    public bool Estatus { get; set; }
    public string Sexo { get; set; }
    public System.DateTime FechaCreacion { get; set; }
}
