//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxsisTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Usuario
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Favor de introducir el correo")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)([a-zA-Z]{2,4})(\.[a-zA-Z]{2,4})?$"
        ,ErrorMessage = "Formato de correo inválido.")]
        [Display(Name = "Correo:")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "Favor de introducir el nombre de usuario")]
        [Display(Name = "Usuario:")]
        public string NombreUsuario { get; set; }
        [Required(ErrorMessage = "Favor de introducir la contraseña")]
        [Display(Name = "Contraseña:")]
        public string Password { get; set; }
        public bool Estatus { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    }
}
